services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: turnos
    ports:
      - 5432:5432

  frontend:
    image: node:22.11.0
    tty: true
    ports:
      - "4200:4200"
    volumes:
      - "./frontend:/var/www"
    working_dir: /var/www

  backend:
    image: node:22.11.0
    tty: true
    ports:
      - "4000:4000"
    volumes:
      - "./backend:/var/www"
    working_dir: /var/www
